import React, { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Brain, TrendingUp, AlertTriangle, FileSearch, Target, Zap } from "lucide-react";
import { PredictiveAnalytics } from "@/components/ai-intelligence/PredictiveAnalytics";
import { PatternRecognition } from "@/components/ai-intelligence/PatternRecognition";
import { DocumentAnalysis } from "@/components/ai-intelligence/DocumentAnalysis";
import { RiskScoring } from "@/components/ai-intelligence/RiskScoring";
import { InsightsGeneration } from "@/components/ai-intelligence/InsightsGeneration";
import { AIPerformanceMetrics } from "@/components/ai-intelligence/AIPerformanceMetrics";

const AIIntelligence = () => {
  const [activeTab, setActiveTab] = useState("dashboard");

  const aiMetrics = [
    {
      title: "Prediction Accuracy",
      value: "94.2%",
      change: "+2.1%",
      icon: Target,
      trend: "up"
    },
    {
      title: "Risks Identified",
      value: "1,247",
      change: "+156",
      icon: AlertTriangle,
      trend: "up"
    },
    {
      title: "Documents Processed",
      value: "5,834",
      change: "+423",
      icon: FileSearch,
      trend: "up"
    },
    {
      title: "Patterns Detected",
      value: "89",
      change: "+12",
      icon: Brain,
      trend: "up"
    }
  ];

  return (
    <div className="container mx-auto p-6 space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">AI Risk Intelligence</h1>
          <p className="text-muted-foreground">
            Advanced AI-powered risk analytics and intelligent automation
          </p>
        </div>
        <div className="flex items-center space-x-2">
          <Badge variant="outline" className="bg-green-50 text-green-700 border-green-200">
            <Zap className="h-3 w-3 mr-1" />
            AI Active
          </Badge>
        </div>
      </div>

      <Tabs value={activeTab} onValueChange={setActiveTab} className="space-y-6">
        <TabsList className="grid w-full grid-cols-6">
          <TabsTrigger value="dashboard">Dashboard</TabsTrigger>
          <TabsTrigger value="predictive">Predictive Analytics</TabsTrigger>
          <TabsTrigger value="patterns">Pattern Recognition</TabsTrigger>
          <TabsTrigger value="documents">Document Analysis</TabsTrigger>
          <TabsTrigger value="scoring">Dynamic Scoring</TabsTrigger>
          <TabsTrigger value="insights">AI Insights</TabsTrigger>
        </TabsList>

        <TabsContent value="dashboard" className="space-y-6">
          {/* AI Metrics Overview */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {aiMetrics.map((metric, index) => (
              <Card key={index}>
                <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                  <CardTitle className="text-sm font-medium">{metric.title}</CardTitle>
                  <metric.icon className="h-4 w-4 text-muted-foreground" />
                </CardHeader>
                <CardContent>
                  <div className="text-2xl font-bold">{metric.value}</div>
                  <p className={`text-xs ${metric.trend === 'up' ? 'text-green-600' : 'text-red-600'}`}>
                    {metric.change} from last month
                  </p>
                </CardContent>
              </Card>
            ))}
          </div>

          {/* AI Performance Overview */}
          <AIPerformanceMetrics />

          {/* Recent AI Insights */}
          <Card>
            <CardHeader>
              <CardTitle>Recent AI Insights</CardTitle>
              <CardDescription>
                Latest automated insights generated by the AI engine
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div className="flex items-start space-x-3 p-4 bg-blue-50 rounded-lg border border-blue-200">
                  <Brain className="h-5 w-5 text-blue-600 mt-0.5" />
                  <div>
                    <h4 className="font-medium text-blue-900">Emerging Risk Pattern Detected</h4>
                    <p className="text-sm text-blue-700 mt-1">
                      AI has identified a correlation between vendor concentration and operational incidents. 
                      Risk probability increased by 23% in Q4.
                    </p>
                    <div className="flex items-center mt-2 space-x-2">
                      <Badge variant="secondary" className="text-xs">High Priority</Badge>
                      <span className="text-xs text-blue-600">2 hours ago</span>
                    </div>
                  </div>
                </div>

                <div className="flex items-start space-x-3 p-4 bg-amber-50 rounded-lg border border-amber-200">
                  <TrendingUp className="h-5 w-5 text-amber-600 mt-0.5" />
                  <div>
                    <h4 className="font-medium text-amber-900">Risk Trend Forecast</h4>
                    <p className="text-sm text-amber-700 mt-1">
                      Predictive models indicate potential cyber risk escalation in next 30 days. 
                      Recommended: Increase monitoring and review security controls.
                    </p>
                    <div className="flex items-center mt-2 space-x-2">
                      <Badge variant="secondary" className="text-xs">Medium Priority</Badge>
                      <span className="text-xs text-amber-600">4 hours ago</span>
                    </div>
                  </div>
                </div>

                <div className="flex items-start space-x-3 p-4 bg-green-50 rounded-lg border border-green-200">
                  <FileSearch className="h-5 w-5 text-green-600 mt-0.5" />
                  <div>
                    <h4 className="font-medium text-green-900">Document Analysis Complete</h4>
                    <p className="text-sm text-green-700 mt-1">
                      Successfully processed 145 new policy documents. Identified 12 compliance gaps 
                      and 8 improvement opportunities.
                    </p>
                    <div className="flex items-center mt-2 space-x-2">
                      <Badge variant="secondary" className="text-xs">Informational</Badge>
                      <span className="text-xs text-green-600">6 hours ago</span>
                    </div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="predictive">
          <PredictiveAnalytics />
        </TabsContent>

        <TabsContent value="patterns">
          <PatternRecognition />
        </TabsContent>

        <TabsContent value="documents">
          <DocumentAnalysis />
        </TabsContent>

        <TabsContent value="scoring">
          <RiskScoring />
        </TabsContent>

        <TabsContent value="insights">
          <InsightsGeneration />
        </TabsContent>
      </Tabs>
    </div>
  );
};

export default AIIntelligence;